version: '3.3'

services:
  postgres:
    image: "postgres:12"
    network_mode: host
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234567"
    ports:
      - "15432:5432"
    shm_size: 1g
